### ISSUE TITLE
Write README.MD

### ISSUE THREAD

**Issue by adriamb** [adriamb/gopad#6]

**Comment by gonzaloserrano** [comment]
I don't know really how to start working with gopad:

```
╰─✘ gopad

                                 _
  __ _   ___   _ __    __ _   __| |
 / _` | / _ \ | '_ \  / _` | / _` |
| (_| || (_) || |_) || (_| || (_| |
 \__, | \___/ | .__/  \__,_| \__,_|
 |___/        |_|
panic: Config file not found: open : no such file or directory
```
And this doesn't help much:
```
╰─✘ gopad --help

                                 _
  __ _   ___   _ __    __ _   __| |
 / _` | / _ \ | '_ \  / _` | / _` |
| (_| || (_) || |_) || (_| || (_| |
 \__, | \___/ | .__/  \__,_| \__,_|
 |___/        |_|
A minimal markdown personal notepad written in go

Usage:
  gopad [flags]

Flags:
      --config string   config file (default is $HOME/.one2merge.yaml)
  -h, --help            help for gopad
```
What's this one2merge config here?
What should i put in the config file?

Thanks

**Comment by adriamb** [comment]
Gonzalo,

At this moment, the configuration file is a file called ```$HOME/.gopad.yaml``` 
With this contents:

```yaml
port: <server port, e.g. 8080>
prefix: <server prefix, left it blank>
auth:
    googleclientid: <google oauth2 clientid>
    allowedemails:
        - <email of allowed oauth client>
        - <email of allowed oauth client>
```

At this moment oauth authentication couldn't be bypassed. Try with clientid 503240060263-o7ahabsmc94bu0lok2qvvvs4rkl4imo9.apps.googleusercontent.com

**Comment by gonzaloserrano** [comment]
I put this in the config file:
```
port: 8086
prefix:
auth:
    googleclientid: 503240060263-o7ahabsmc94bu0lok2qvvvs4rkl4imo9.apps.googleusercontent.com
    allowedemails:
        - mymail@gmail.com
```
and then
```
╰─✘ gopad --config ~/.gopad.yaml

                                 _
  __ _   ___   _ __    __ _   __| |
 / _` | / _ \ | '_ \  / _` | / _` |
| (_| || (_) || |_) || (_| || (_| |
 \__, | \___/ | .__/  \__,_| \__,_|
 |___/        |_|
Using config file: /Users/gonzalo/.gopad.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

panic: html/template: pattern matches no files: `web/templates/*`
```
